version: '3.9'

services:
  frontend:
    image: frontend
    restart: always
    ports:
      - 80:5173
    environment:
      - DB_HOST=db
      - DB_USER=hest
      - DB_PASS=hest
      - DB_NAME=zay_dev
    networks:
      - network

  backend:
    image: backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=zay_dev
    command: sh -c "npm run db:migrate && npm run db:seed && npm start"
    networks:
      - network

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=zay_dev
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network

networks:
  network:

volumes:
  db_data: